### ISSUE TITLE
cvat with certbot issued SSL certificate

### ISSUE THREAD

**Issue by smokedsalmonbagel** [openvinotoolkit/cvat#1172]
I explored a few options for using a certbot generated SSL cert from letsencrypt.  I have a an almost working prototype...  

My nginx conf looks like this:
```
server {
    listen              443 ssl;
    server_name         mydomain.com;
    ssl_certificate     /etc/letsencrypt/live/mydomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;
	root /usr/share/nginx/html;
    location / {
		try_files $uri $uri/ /index.html;
		add_header Access-Control-Allow-Origin "*";
    }
}
```
[note: There is another conf file for doing the cert renewal (port 80 only):]

when I goto `mydomain.com` the cvat login loads with the message:
```
Could not check authorization on the server
Open the Browser Console to get details
```
It looks like all the network requests from the browser are 200.
![image](https://user-images.githubusercontent.com/5355848/74997282-bc6bee80-5423-11ea-8233-f5f239f07ec8.png)
but the console reports
```
TypeError: Cannot use 'in' operator to search for 'id' in <!DOCTYPE html>
``` 
I have changed the following in docker-compose.yml based on what others have posted to get remote installations working.
```
cvat_ui:
    build:
      args:
        REACT_APP_API_PROTOCOL: https
        REACT_APP_API_HOST: mydomain.com
        REACT_APP_API_PORT: 
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: a@a.com
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
```

I know there are a few other issues out there regarding SSL, but haven't seen anything about the console error above.

**Comment by azhavoro** [comment]
@smokedsalmonbagel could you please provide also docker-compose config for the cvat service?

**Comment by smokedsalmonbagel** [comment]
Sure, here is my full dockercompose yml file:
```
version: "2.3"

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    networks:
      default:
        aliases:
          - redis
    restart: always

  cvat:
    container_name: cvat
    image: cvat
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    ports:
      - "8080:8080"
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
        TF_ANNOTATION: "no"
        AUTO_SEGMENTATION: "no"
        USER: "django"
        DJANGO_CONFIGURATION: "production"
        TZ: "Etc/UTC"
        OPENVINO_TOOLKIT: "no"
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ""
      UI_SCHEME: http
      UI_HOST: localhost
      UI_PORT: 7080


    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - cvat_models:/home/django/models

  cvat_ui:
    container_name: cvat_ui
    image: nginx
    restart: always
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
        REACT_APP_API_PROTOCOL: https
        REACT_APP_API_HOST: mydomain.com
        REACT_APP_API_PORT: 
      dockerfile: Dockerfile.ui

    networks:
      default:
        aliases:
          - ui
    depends_on:
      - cvat
    ports:
      - "7080:80"
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: a@a.com
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_models:
  letsencrypt:
  conf.d:
```
