### ISSUE TITLE
"Serving over HTTPS" instructions possible mistake

### ISSUE THREAD

**Issue by ilouzl** [openvinotoolkit/cvat#1903]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
There is a possible mistake in some of the steps of the above HTTPS setup instructions.

### Expected Behaviour

The serving over https instructions to be as accurate as possible.

### Current Behaviour

acme.sh is being installed by default at $HOME, and therefore all issued certificates are placed in this path.  
Following the instructions, [after testing](https://github.com/opencv/cvat/blob/159eeb974fa378277529b44efba0bb88e3b163d3/cvat/apps/documentation/installation.md#L435) Letsencrypt's certificates creation using stating environment, we need to delete the staging certificates before creating new ones. The manual prompts to delete the files from 
```rm -r /root/.acme.sh/my-cvat-server.org```
while they were actually created in 
```$HOME/.acme.sh/my-cvat-server.org```.

Also, the wrong folder is mounted as a volume to the contained in the docker-compose.override.yml.
### Possible Solution

1. Change ```rm -r /root/.acme.sh/my-cvat-server.org``` to ```rm -r $HOME/.acme.sh/my-cvat-server.org```.
2. Use  docker-compose.override.yml:
```
version: "2.3"

services:
  cvat_proxy:
    environment:
      CVAT_HOST: my-cvat-server.org
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt-webroot:/var/tmp/letsencrypt-webroot
      - ~/.acme.sh:/root/.acme.sh

  cvat:
    environment:
      ALLOWED_HOSTS: '*'
```

### Steps to Reproduce (for bugs)

Just follow the [Serving over HTTPS instructions](https://github.com/opencv/cvat/blob/159eeb974fa378277529b44efba0bb88e3b163d3/cvat/apps/documentation/installation.md#serving-over-https)

### Context

cvat_proxy will fail starting properly using the original instructions, since no certificates are found at ```/root/.acme.sh```. 
### Your Environment

- Git hash commit (`git log -1`): https://github.com/opencv/cvat/commit/f1b01780cca03cbba31960f593c1522884f89e35
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18
- Code example or link to GitHub repo or gist to reproduce problem: 
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.
