### ISSUE TITLE
Server Error while running cvat on local ubuntu machine for automatic annotation

### ISSUE THREAD

**Issue by varchanaiyer** [openvinotoolkit/cvat#2182]
[docker_logs.txt](https://github.com/openvinotoolkit/cvat/files/5224049/docker_logs.txt)
[nuctlgetfunction.txt](https://github.com/openvinotoolkit/cvat/files/5224053/nuctlgetfunction.txt)
[dockerpsoutput.txt](https://github.com/openvinotoolkit/cvat/files/5224058/dockerpsoutput.txt)

### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Trying automatic annotation using CVAT. 
I accessed the cvat in localhost:8080. Nuclio is running and has uploaded all models successfully. I am able to create tasks. After that once I click on automatic annotation, it shows the set of models(like Faster RCNN, Yolo etc too).
However, when I run any model it shows the error: 
```
Error: Inference status for the task 2 is failed. requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://nuclio:8070/api/function_invocations
```

### Expected Behaviour

Ideally, it should run the model and annotate the images. 

### Current Behaviour
Currently it is just throwing an error, whenever I try to run the pre loaded models for automatic annotation
### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`): Using latest CVAT version 
- Docker version `docker version` (e.g. Docker 17.0.05):  Docker version  19.03.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS):  Ubuntu 18.04.5 LTS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by varchanaiyer** [comment]
Hi closing this as, it was a proxy issue.

On the docker compose file, added an extra site to surpass proxy under the `no_proxy: 172.28.0.1,<your invocation url>, ${no_proxy}` line.

The invocation url from nuclio dashboard has to be added to the above line, so that it surpasses the proxy of your network.

**Comment by rathishkumar** [comment]
@varchanaiyer I am facing the same issue, can you please share exactly where it needs to be configured. I could not see no_proxy variable in docker compose file. I have it in `docker service` and `~/.docker/config.json` file. But it is not taking this variable from these locations.

**Comment by rathishkumar** [comment]
`"internalInvocationURLs": ["172.17.0.5"]` added the IP address to `components/serverless/docker-compose.serverless.yml` still getting the same error `"503 Server Error: Service Unavailable for url: http://nuclio:8070/api/function_invocations"`

`docker-compose:`

```
version: '3.3'
services:
  serverless:
    container_name: nuclio
    image: quay.io/nuclio/dashboard:1.6.8-amd64
    restart: always
    networks:
      default:
        aliases:
          - nuclio
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      http_proxy:
      https_proxy:
      no_proxy: 172.28.0.1,172.17.0.4,172.17.0.0/24,${no_proxy}
      NUCLIO_CHECK_FUNCTION_CONTAINERS_HEALTHINESS: 'true'
      NUCLIO_DASHBOARD_DEFAULT_FUNCTION_MOUNT_MODE: 'volume'
    ports:
      - '8070:8070'
  cvat:
    environment:
      CVAT_SERVERLESS: 1
      no_proxy: kibana,logstash,nuclio,${no_proxy}
volumes:
  cvat_events:
```

Any suggestions?
