### ISSUE TITLE
LDAP Integration settings.py

### ISSUE THREAD

**Issue by poojitha102424** [openvinotoolkit/cvat#2239]
Hello Team,

I have gone through "Add instruction to enable LDAP auth"

I am integrating LDAP with one of my CVAT applications. 

Where should I put the settings.py file to be picked up by build via docker-compose?

**Comment by poojitha102424** [comment]
Hello Team,

 How to check if cvat container is actually picking up the settings.py file ?

**Comment by azhavoro** [comment]
@poojitha102424 Hi, sorry for the late response.
You need to bind new settings.py file into `/home/django/settings.py` and specify env variable `DJANGO_SETTINGS_MODULE` to use new settings. Like this:
```yml
services:
  cvat:
    build:
      args:
    environment:
      DJANGO_SETTINGS_MODULE: settings
    volumes:
      settings.py:/home/django/settings.py:ro
```
