### ISSUE TITLE
Service 'cvat_ui' failed build at a VM(Ubuntu 18.04 OS) on Google Cloud

### ISSUE THREAD

**Issue by stoneMo** [openvinotoolkit/cvat#2365]
When I `sudo docker-compose build ` at VM (Ubuntu 18.04 OS) on Google Cloud, I got this error `Service 'cvat_ui' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1`. Could somebody help me figure out what I should do next? I have read our issues and tried several ways to solve it. But it still did not work. Here are the logs. 

Building: /usr/local/bin/node /tmp/cvat-canvas/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/tmp/cvat-canvas/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/tmp/cvat-canvas/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/tmp/cvat-canvas/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/tmp/cvat-canvas/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/which/which.js:89:16
gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/tmp/cvat-canvas/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/tmp/cvat-canvas/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/tmp/cvat-canvas/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/which/which.js:89:16
gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/tmp/cvat-canvas/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/tmp/cvat-canvas/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/tmp/cvat-canvas/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/which/which.js:89:16
gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (/tmp/cvat-canvas/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/tmp/cvat-canvas/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/tmp/cvat-canvas/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/which/which.js:89:16
gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /tmp/cvat-canvas/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/tmp/cvat-canvas/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/tmp/cvat-canvas/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/tmp/cvat-canvas/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/tmp/cvat-canvas/node_modules/which/which.js:80:29)
gyp ERR! stack     at /tmp/cvat-canvas/node_modules/which/which.js:89:16
gyp ERR! stack     at /tmp/cvat-canvas/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /tmp/cvat-canvas/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Linux 5.4.0-1028-gcp
gyp ERR! command "/usr/local/bin/node" "/tmp/cvat-canvas/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /tmp/cvat-canvas/node_modules/node-sass
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm info lifecycle node-sass@4.13.1~postinstall: Failed to exec postinstall script
npm timing action:postinstall Completed in 834ms
npm timing stage:rollbackFailedOptional Completed in 199ms
npm timing stage:runTopLevelLifecycles Completed in 21429ms
npm WARN cvat-canvas@2.1.3 No repository field.
npm WARN cvat-canvas@2.1.3 scripts['server'] should probably be scripts['start'].
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 22973ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-28T05_56_36_720Z-debug.log

**Comment by bsekachev** [comment]
Looks like the same issue on our Travis CI.

**Comment by bsekachev** [comment]
The issue with ``node-sass`` package. Updating to a newer version 4.14.1 helped. The PR #2367

**Comment by stoneMo** [comment]
@bsekachev Thanks for your suggestion. But I have updated `node-sass` to the new version, and I still had this issue.

**Comment by bsekachev** [comment]
@stoneMo Have you updated it in both ``cvat-ui`` and ``cvat-canvas`` modules?

**Comment by stoneMo** [comment]
> cvat-ui

I just `sudo npm install node-sass` in my terminal. How could I update it both in `cvat-ui`and `cvat-canvas` modules.

**Comment by bsekachev** [comment]
Just pull changes from develop and rebuild

**Comment by stoneMo** [comment]
@bsekachev Thanks for your solution. I successfully installed the CVAT on my VM. But I met issues with logging into the admin page using`localhost:8080`. Could you give me some suggestions? 

![image](https://user-images.githubusercontent.com/59949790/97438226-7a565d80-195f-11eb-8a28-c72552c78f1b.png)

**Comment by bsekachev** [comment]
What kind of issues have you met there?

**Comment by stoneMo** [comment]
My admin page http://104.199.181.135:8080/admin is not reachable. 
Here is my docker-compose.yml. 

```
#
# Copyright (C) 2018-2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
version: '3.3'

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    networks:
      default:
        aliases:
          - redis
    restart: always

  cvat:
    container_name: cvat
    image: cvat/server
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy: nuclio,${no_proxy}
        socks_proxy:
        USER: 'django'
        DJANGO_CONFIGURATION: 'production'
        TZ: 'Etc/UTC'
        CLAM_AV: 'no'
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ''
      ALLOWED_HOSTS: '*'
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - cvat_models:/home/django/models

  cvat_ui:
    container_name: cvat_ui
    image: cvat/ui
    restart: always
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
      dockerfile: Dockerfile.ui

    networks:
      default:
        aliases:
          - ui
    depends_on:
      - cvat

  cvat_proxy:
    container_name: cvat_proxy
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - cvat
      - cvat_ui
    environment:
      CVAT_HOST: 104.199.181.135
    ports:
      - '8080:80'
    volumes:
      - ./cvat_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cvat_proxy/conf.d/cvat.conf.template:/etc/nginx/conf.d/cvat.conf.template:ro
    command: /bin/sh -c "envsubst '$$CVAT_HOST' < /etc/nginx/conf.d/cvat.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_models:


```

Here is my docker-compose.override.yml.

```
version: "3.3"

services:
  cvat_proxy:
    environment:
      CVAT_HOST: 104.199.181.135
```
