### ISSUE TITLE
Traefik and duckdns setup

### ISSUE THREAD

**Issue by MarioProjects** [openvinotoolkit/cvat#2610]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Trying to setup Traefik with duckdns Gateway error

### Expected Behaviour

Get working CVAT

### Current Behaviour

Not working CVAT -> Bad Gateway

### Possible Solution

A proper configuration

### Steps to Reproduce (for bugs)

1. git clone https://github.com/opencv/cvat
2. cd cvat
3. docker-compose build
4. docker-compose.override.yml
```
version: '3.3'

services:
  cvat_proxy:
    environment:
      CVAT_HOST: cvat.example.duckdns.org
```
5. docker-compose.yml (modified following)
```
# --- Removed networks section and put that ---
networks:
  web:
    external: true
  internal:
    external: false

# --- Under cvat-proxy: ---
ports:
      - '3750:80'
labels:
      - traefik.http.routers.cvat.rule=Host(`cvat.example.duckdns.org`)
      - traefik.http.routers.cvat.tls=true
      - traefik.http.routers.cvat.tls.certresolver=lets-encrypt
      - traefik.port=3750
networks:
      - internal
      - web

# -- Modified all services -> cvat_db, cvat_redis... networks to  (maybe this is wrong, removing aliases) --
networks:
      - internal
      - web
```
6. docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml -f docker-compose.override.yml up -d --build

### Your Environment

- Git hash commit (`git log -1`): commit 48b6da93615f7c2b0a8a4ea9f3c9ae55bb6ed3ae
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.1
- Are you using Docker Swarm or Kubernetes? Docker
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by MarioProjects** [comment]
I think that may be related with networks, if I could add internal and web to the default one you specified with the aliases 'ui' and so on

**Comment by MarioProjects** [comment]
I followed this guide to setup traefik -> https://www.digitalocean.com/community/tutorials/how-to-use-traefik-v2-as-a-reverse-proxy-for-docker-containers-on-ubuntu-20-04#step-3-%E2%80%94-registering-containers-with-traefik

**Comment by MarioProjects** [comment]
If I set my public address I can access

**Comment by MarioProjects** [comment]
Solution: Traefik is not needed for that?! With next at `docker-compose.override.yml` file I am able to access `cvat.myname.duckdns.org:3710`.

```
version: '3.3'

services:
  cvat_proxy:
    environment:
      CVAT_HOST: cvat.myname.duckdns.org
    ports:
      - '3710:80'
    volumes:
      - ./letsencrypt-webroot:/var/tmp/letsencrypt-webroot
      - /root/.acme.sh:/root/.acme.sh

  cvat:
    environment:
      ALLOWED_HOSTS: '*'
```

Last question is, If I wont use 3710, only host name, if I set ports 80:80 it says `ERROR: for cvat_proxy  Cannot start service cvat_proxy: driver failed programming external connectivity on endpoint cvat_proxy (6bd422d9878e2861467ff18715bc99669e05aabaea7221ea6d9923b34744cd15): Bind for 0.0.0.0:80 failed: port is already allocated`
