### ISSUE TITLE
Global network deployment not working

### ISSUE THREAD

**Issue by bax533** [openvinotoolkit/cvat#2985]
I am trying to deploy cvat to be visible globally from my local machine. I followed the installation guide and everything seems to be working on localhost when connecting to `localhost:8888`.

I have set the docker-compose-override.yml to
```
version: '3.3'

services:
  cvat_proxy:
    environment:
      CVAT_HOST: <public_ip_of_my_machine>
```
then run

```
docker-compose down
docker-compose -f docker-compose.yml -f docker-compose-override.yml build
docker-compose -f docker-compose.yml -f docker-compose-override.yml up -d
```
but now when I'm trying to connect to `<public_ip_of_my_machine>:8888` it doesn't load. What am I missing or doing wrong?
