### ISSUE TITLE
Cannot access CVAT by https

### ISSUE THREAD

**Issue by joon612** [openvinotoolkit/cvat#3240]
### My actions before raising this issue
- [ √] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ √] Searched [past issues](/issues)

### Expected Behaviour

Access CVAT by https succesfully.
### Current Behaviour

I cannot accesc CVAT by https, but I can access CVAT by http8080.

### Steps to Reproduce (for bugs)

1. I followed the 'installation.md' to set my site support https.
2. Before using 'acme.sh', everything was fine. But acme.sh doesn't work me, it throw an error about cannot access one site. I checked reason is sh want to access by 80, but my site default port is 8080.
3. So I want to create certificates by myself. 
```
openssl genrsa -des3 -out server.key 1024                                            
openssl req -new -key server.key -out server.csr                                     
openssl rsa -in server.key -out server_nopwd.key                                     
openssl x509 -req -days 1825 -in server.csr -signkey server_nopwd.key -out server.crt
```
4. I modified the yml file in linux. Here are them content:
- cvat/docker-compose.override.yml:
```
version: "3.3"

services:
  cvat:
    volumes:
      - cvat_share:/home/django/share:ro
      - cvat_data:/home/django/data
    environment:
      CVAT_SHARE_URL: "Mounted from /home/v-qib/share host directory"
      ALLOWED_HOSTS: '*'
  cvat_proxy:
    environment:
      CVAT_HOST: acvcvat.eastus.cloudapp.azure.com
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./letsencrypt-webroot:/var/tmp/letsencrypt-webroot
      - /etc/ssl/private:/etc/ssl/private
volumes:
  cvat_data:
    driver_opts:
      type: none
      device: /home/v-qib/data
      o: bind
  cvat_share:
    driver_opts:
      type: none
      device: /home/v-qib/share
      o: bind

```
- cvat/docker-compose.yml
```
#
# Copyright (C) 2018-2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
version: '3.3'

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    networks:
      default:
        aliases:
          - redis
    restart: always

  cvat:
    container_name: cvat
    image: openvino/cvat_server
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ''
      ALLOWED_HOSTS: '*'
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs

  cvat_ui:
    container_name: cvat_ui
    image: openvino/cvat_ui
    restart: always
    networks:
      default:
        aliases:
          - ui
    depends_on:
      - cvat

  cvat_proxy:
    container_name: cvat_proxy
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - cvat
      - cvat_ui
    environment:
      CVAT_HOST: localhost
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./cvat_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cvat_proxy/conf.d/cvat.conf.template:/etc/nginx/conf.d/cvat.conf.template:ro
    command: /bin/sh -c "envsubst '$$CVAT_HOST' < /etc/nginx/conf.d/cvat.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:

```
- cvat/cvat_proxy/conf.d/cvat.conf.template
```
server {
    listen       80;
    server_name  _ default;
    return       404;
}

server {
    listen       80;
    server_name  ${CVAT_HOST};

    proxy_pass_header       X-CSRFToken;
    proxy_set_header        Host $http_host;
    proxy_pass_header       Set-Cookie;

    location ^~ /.well-known/acme-challenge/ {
      default_type "text/plain";
      root /var/tmp/letsencrypt-webroot;
    }

    location ~* /api/.*|git/.*|opencv/.*|analytics/.*|static/.*|admin(?:/(.*))?.*|documentation/.*|django-rq(?:/(.*))? {
        proxy_pass              http://cvat:8080;
    }

    location / {
        proxy_pass              http://cvat_ui;
    }
}

server {
    listen 443 ssl;
    server_name ${CVAT_HOST};

    ssl_certificate /etc/ssl/private/server.crt;
    ssl_certificate_key /etc/ssl/private/server_nopwd.key;


    # security options
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;


    proxy_pass_header       X-CSRFToken;
    proxy_set_header        Host $http_host;
    proxy_pass_header       Set-Cookie;

    location ~* /api/.*|git/.*|analytics/.*|static/.*|admin(?:/(.*))?.*|documentation/.*|django-rq(?:/(.*))? {
        proxy_pass              http://cvat:8080;
    }

    location / {
        proxy_pass              http://cvat_ui;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

```
For now, I just want to use both http and https, so I set like above.

I build dockers by command: 
`docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml -f docker-compose.override.yml up -d --build`
'docker ps -a '
```
edbd82f27f0c        nginx:stable-alpine                    "/docker-entrypoint.…"   18 minutes ago      Up 17 minutes                           0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8080->80/tcp   cvat_proxy
8b130cdb6d20        openvino/cvat_ui                       "/docker-entrypoint.…"   18 minutes ago      Up 18 minutes                           80/tcp                                                           cvat_ui
ab58e8fc2929        openvino/cvat_server                   "/usr/bin/supervisord"   18 minutes ago      Up 18 minutes                           8080/tcp                                                         cvat
8b1c03c2cb37        redis:4.0-alpine                       "docker-entrypoint.s…"   18 minutes ago      Up 18 minutes                           6379/tcp                                                         cvat_redis
2b5acee8676c        postgres:10-alpine                     "docker-entrypoint.s…"   18 minutes ago      Up 18 minutes                           5432/tcp                                                         cvat_db
889ff375c825        cvat_elasticsearch                     "/usr/local/bin/dock…"   58 minutes ago      Restarting (1) Less than a second ago                                                                    cvat_elasticsearch
6e527b159890        cvat_logstash                          "/usr/local/bin/dock…"   About an hour ago   Up About an hour                        5044/tcp, 8080/tcp, 9600/tcp                                     cvat_logstash
5bcb04cbada3        openvino/cvat_server                   "bash wait-for-it.sh…"   24 hours ago        Up 24 hours                             8080/tcp                                                         cvat_kibana_setup
c860f6ee1ffa        cvat_kibana                            "/usr/local/bin/kiba…"   7 months ago        Up 5 days                                                                                                cvat_kibana
```

### Your Environment

- Git hash commit (`git log -1`):
```
commit c7033a79ecf0e67c224a83a8b5431e0f1169de98 (HEAD, tag: v1.3.0)
Merge: b260661a d1a4cfb7
Author: Nikita Manovich <nikita.manovich@intel.com>
Date:   Wed Mar 31 23:54:50 2021 +0300

    Merge branch 'release-1.3.0'
```
- Docker version `docker version` (e.g. Docker 17.0.05):
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
 Linux
- Code example or link to GitHub repo or gist to reproduce problem:
 I followed this doc: https://github.com/openvinotoolkit/cvat/blob/develop/site/content/en/docs/for-users/installation.md

Please help me fix this probem, thanks.
