### ISSUE TITLE
Multiple CVAT_host

### ISSUE THREAD

**Issue by arcibiyo** [openvinotoolkit/cvat#3390]
I wanna connect to the cvat interface from 2 different ip addresses like below photo. How can ı solve this situation? 

![cvat_host](https://user-images.githubusercontent.com/47760055/124499669-15dd7f00-ddc7-11eb-9b51-b80ce6367314.png)

**Comment by azhavoro** [comment]
https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-specify-multiple-hostnames-for-cvat_host

**Comment by arcibiyo** [comment]
@azhavoro so thanks

**Comment by EytanDn** [comment]
> https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-specify-multiple-hostnames-for-cvat_host

Link is broken, Help required please

**Comment by EytanDn** [comment]
> https://opencv.github.io/cvat/docs/faq/#how-to-specify-multiple-hostnames

Thank you! 
I have in fact later that day come across this article, though did not succeed in configuring the dual host.

we host a local instance (v2.4.2)  on companies machine, and require access from both a local IP and VPN IP.
I've followed the guide but when booting up I would lose access to the instance on both IPs, and instead get a 404 error when
attempting to connect

docker-compose.override.yml:
```
 cvat:
    labels:
      - traefik.http.routers.cvat.rule=(Host(`192.168.x.xxx`) || Host(`172.xxx.xxx.xxx`)) &&
          PathPrefix(`/api/`, `/git/`, `/opencv/`, `/analytics/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)

  cvat_ui:
    labels:
      - traefik.http.routers.cvat-ui.rule=Host(`192.168.x.xxx`) || Host(`172.xxx.xxx.xxx`)
```

a few possible points of failure that aren't made clear by the guide:
- under this configuration, what should the value of CVAT_HOST be?
- should there be any value put to ALLOWED_HOSTS?
- should the change (mentioned above) be in the default docker compose file or in the override file?

thank you very much for the help

**Comment by nmanovic** [comment]
@azhavoro , could you please advise?

**Comment by whittenator** [comment]
I am having this same exact issue with the latest release as well. I attempted to follow the guide as well with a very similar docker-compose.yml to @EytanDn but now both IPs fail. If I revert back to the original and do a single IP, it works. Any ideas?

**Comment by whittenator** [comment]
> I am having this same exact issue with the latest release as well. I attempted to follow the guide as well with a very similar docker-compose.yml to [@EytanDn](https://github.com/EytanDn) but now both IPs fail. If I revert back to the original and do a single IP, it works. Any ideas?

Actually I just figured it out, I was missing the parenthesis surrounding the two hosts. It looks like @EytanDn correctly did the cvat_server but the cvat_ui was missing the parenthesis. This is what it should look like:
```YAML
 cvat:
    labels:
      - traefik.http.routers.cvat.rule=(Host(`192.168.x.xxx`) || Host(`172.xxx.xxx.xxx`)) &&
          PathPrefix(`/api/`, `/git/`, `/opencv/`, `/analytics/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)

  cvat_ui:
    labels:
      - traefik.http.routers.cvat-ui.rule=Host((`192.168.x.xxx`) || Host(`172.xxx.xxx.xxx`))
```
