### ISSUE TITLE
How to Label rotating box?

### ISSUE THREAD

**Issue by wangzyon** [openvinotoolkit/cvat#4006]
I read the link below, but I can't find the `rotation point` in the software，Could you provide more detailed description documents , operation screenshots or branch version number？Many thanks.
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/annotation-with-rectangles/#rotation-rectangle

![image](https://user-images.githubusercontent.com/36832126/145752286-871aca23-caec-4b68-a507-aa4c478a0b44.png)

**Comment by bsekachev** [comment]
Hi @wangzyon 

Maybe your version is not updated. 
It was not realeased yet, but the feature can be used if install CVAT from develop branch.

**Comment by wangzyon** [comment]
I install CVAT from develop branch. but I still can't find the rotation point in the software，I don't see any difference in the toolbar

**Comment by wangzyon** [comment]
Could you provide some rotating operation screenshots？Many thanks

**Comment by nmanovic** [comment]
https://openvinotoolkit.github.io/cvat/docs/manual/advanced/annotation-with-rectangles/#rotation-rectangle

**Comment by wangzyon** [comment]
> https://openvinotoolkit.github.io/cvat/docs/manual/advanced/annotation-with-rectangles/#rotation-rectangle

```
$ git branch
* develop

$ git log -1
commit 1d952acee8dbce679daac99ff615b8bec2b3cbf9 (HEAD -> develop)
Author: Dmitry Kalinin <dmitry.kalinin@intel.com>
Date:   Thu Dec 2 07:07:04 2021 +0300

    Issue deleting (#3952)

docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.override.yml up -d --build
```

docker-compose.override.yml
```
version: "3.3"
services:
  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from /home/cv/volume/cvat_volume" # 标注平台挂载的本地数据卷
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - cvat_models:/home/django/models
      - cvat_share:/home/django/share:ro # 新加

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_models:
  cvat_share:
    driver_opts:
      type: none
      device: /home/cv/volume/cvat_volume
      o: bind
```

 I can't find the `rotation point` in the software
