### ISSUE TITLE
502 Bad Gateway after update

### ISSUE THREAD

**Issue by mrKallah** [openvinotoolkit/cvat#4504]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Possibly related to #3948

Since updating from a version from early January today, I have been greeted with a 502 Bad Gateway. I am using 'export CVAT_HOST=192.168.14.190' to select ip and 'sudo -E docker-compose -f docker-compose.yml -f docker-compose.dev.yml build' to build. With 'sudo -E docker-compose up -d' to start it. Below is my docker-compose-dev.yml:

```
version: '3.3'

services:
  cvat:
    environment:
      CVAT_SHARE_URL: 'Mounted from /mnt/share host directory'
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /mnt/meridia/videos/videos/
      o: bind

```
and the output from the chrome debugger is below:
```
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
cvat-ui.745e17d87182d0fac7ac.min.js:sourcemap:393 Error: Request failed with status code 502. "Bad Gateway".
e @ cvat-ui.745e17d87182d0fac7ac.min.js:sourcemap:393
:8080/api/auth/password/change?org=:1          Failed to load resource: the server responded with a status of 502 (Bad Gateway)
:8080/api/auth/password/reset?org=:1          Failed to load resource: the server responded with a status of 502 (Bad Gateway)
:8080/api/restrictions/user-agreements?org=:1          Failed to load resource: the server responded with a status of 502 (Bad Gateway)
cvat-ui.745e17d87182d0fac7ac.min.js:sourcemap:393 Error: Request failed with status code 502. "Bad Gateway".
```

I have tried to use an incognito mode window to ensure its not to do with my cookies and I have tried to restart the machine, but with no luck. I'd be happy to supply any other information that may be helpful to figuring out what is wrong. 

### Expected Behaviour

No error

### Current Behaviour

Error

### Possible Solution

None that I have found, maybe delete docker image and restart

### Steps to Reproduce (for bugs)

1. Not sure if possible

### Your Environment

- Git hash commit (`git log -1`): bceae228a79bfa149eda95403c4e0813d63b92aa
- Docker version `docker version` (e.g. Docker 17.0.05):20.10.13
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu Server 20.04.4 LTS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.
